"""Emit the design tokens as CSS custom properties and Plotly templates.

``design/tokens.json`` is the single source of truth. This script writes

    assets/tokens.css          the custom properties, the two colour schemes
                               and the @font-face rules
    src/plotly_template.py     the light and dark Plotly templates and the
                               token dictionary the theme module reads

Both files are committed so that the deployment needs no build step.
``tests/test_tokens.py`` rebuilds them in memory and fails when either
committed file differs from the output, so the three files cannot drift
apart. Run ``uv run python scripts/build_tokens.py`` after editing the
tokens; ``--check`` reports staleness without writing.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS_PATH = ROOT / "design" / "tokens.json"
CSS_PATH = ROOT / "assets" / "tokens.css"
TEMPLATE_PATH = ROOT / "src" / "plotly_template.py"

HEADER = "Generated by scripts/build_tokens.py from design/tokens.json. Do not edit by hand."


def load_tokens(path: Path = TOKENS_PATH) -> dict:
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def rgba(hex_colour: str, alpha: float) -> str:
    value = hex_colour.lstrip("#")
    red, green, blue = (int(value[i : i + 2], 16) for i in (0, 2, 4))
    return f"rgba({red},{green},{blue},{alpha})"


def _rem(base_px: int, ratio: float, step: int) -> str:
    return f"{ratio**step:.4f}rem".replace(".0000rem", "rem")


def _font_stack(font: dict) -> str:
    return f'"{font["family"]}", {font["fallback"]}'


def scheme_data(tokens: dict, scheme_name: str) -> dict:
    """The data colours of one scheme: ``data`` with ``data_dark`` laid over it for dark."""
    data = dict(tokens["data"])
    if scheme_name == "dark":
        data.update(tokens.get("data_dark", {}))
    return data


def band_fills(data: dict) -> dict[str, str]:
    """The band fill per phase as an rgba string, from the hue and opacity."""
    return {
        phase: rgba(data["phase"][phase], alpha) for phase, alpha in data["phase_opacity"].items()
    }


def _scheme_block(scheme: dict, data: dict) -> list[str]:
    lines = [f"  --{key.replace('_', '-')}: {value};" for key, value in scheme.items()]
    for phase, colour in data["phase"].items():
        lines.append(f"  --phase-{phase.replace('_', '-')}: {colour};")
    for phase, fill in band_fills(data).items():
        lines.append(f"  --band-{phase.replace('_', '-')}: {fill};")
    for state, colour in data["state"].items():
        lines.append(f"  --state-{state.replace('_', '-')}: {colour};")
    for index, colour in enumerate(data["series"], start=1):
        lines.append(f"  --series-{index}: {colour};")
    lines.append(f"  --index-primary: {data['index']['primary']};")
    lines.append(f"  --index-secondary: {data['index']['secondary']};")
    lines.append(f"  --threshold: {data['threshold']};")
    return lines


def build_css(tokens: dict) -> str:
    font = tokens["font"]
    space = tokens["space"]
    layout = tokens["layout"]
    motion = tokens["motion"]
    light = tokens["scheme"]["light"]
    dark = tokens["scheme"]["dark"]

    out: list[str] = [f"/* {HEADER} */", ""]
    for role in ("display", "text"):
        face = font[role]
        out += [
            "@font-face {",
            f'  font-family: "{face["family"]}";',
            f'  src: url("fonts/{face["file"]}") format("woff2");',
            f"  font-weight: {face['weight_range']};",
            "  font-style: normal;",
            "  font-display: swap;",
            "}",
            "",
        ]
    out.append(":root {")
    out.append(f"  --font-display: {_font_stack(font['display'])};")
    out.append(f"  --font-text: {_font_stack(font['text'])};")
    out.append(f"  --font-base: {font['base_px']}px;")
    for name, step in font["steps"].items():
        out.append(f"  --text-{name}: {_rem(font['base_px'], font['ratio'], step)};")
    for name, value in font["line_height"].items():
        out.append(f"  --leading-{name}: {value};")
    out.append(f"  --measure: {font['measure']};")
    for step in space["steps"]:
        out.append(f"  --space-{step}: {step * space['unit_px']}px;")
    for key, value in layout.items():
        name = key.replace("_px", "").replace("_", "-")
        out.append(f"  --{name}: {value}px;")
    out.append(f"  --motion-fast: {motion['fast_ms']}ms;")
    out.append(f"  --motion: {motion['base_ms']}ms;")
    out.append(f"  --easing: {motion['easing']};")
    out += _scheme_block(light, scheme_data(tokens, "light"))
    out.append("  color-scheme: light;")
    out.append("}")
    out.append("")
    dark_data = scheme_data(tokens, "dark")
    out.append("@media (prefers-color-scheme: dark) {")
    out.append('  :root:not([data-theme="light"]) {')
    out += ["  " + line for line in _scheme_block(dark, dark_data)]
    out.append("    color-scheme: dark;")
    out.append("  }")
    out.append("}")
    out.append("")
    out.append(':root[data-theme="dark"] {')
    out += _scheme_block(dark, dark_data)
    out.append("  color-scheme: dark;")
    out.append("}")
    out.append("")
    out.append("@media (prefers-reduced-motion: reduce) {")
    out.append("  :root {")
    out.append("    --motion-fast: 0ms;")
    out.append("    --motion: 0ms;")
    out.append("  }")
    out.append("}")
    return "\n".join(out) + "\n"


def build_template(tokens: dict, scheme_name: str) -> dict:
    """The Plotly template for one scheme as a plain dictionary."""
    scheme = tokens["scheme"][scheme_name]
    data = scheme_data(tokens, scheme_name)
    font = tokens["font"]
    border_key = "border_dark" if scheme_name == "dark" else "border_light"
    axis = {
        "gridcolor": scheme["grid"],
        "zerolinecolor": scheme["grid"],
        "linecolor": scheme["rule"],
        "tickcolor": scheme["ink_muted"],
        "tickfont": {"color": scheme["ink_muted"]},
        "title": {"font": {"color": scheme["ink_muted"]}},
        "automargin": True,
    }
    return {
        "layout": {
            "paper_bgcolor": scheme["surface"],
            "plot_bgcolor": scheme["surface"],
            "font": {
                "family": _font_stack(font["text"]),
                "color": scheme["ink"],
                "size": font["figure_font_px"],
            },
            "title": {"font": {"family": _font_stack(font["display"]), "color": scheme["ink"]}},
            "colorway": list(data["series"]),
            "xaxis": dict(axis),
            "yaxis": dict(axis),
            "legend": {
                "bgcolor": "rgba(0,0,0,0)",
                "font": {"color": scheme["ink"]},
                "itemclick": "toggleothers",
                "itemdoubleclick": "toggle",
            },
            "hoverlabel": {
                "bgcolor": scheme["surface"],
                "bordercolor": scheme["rule"],
                "font": {"family": _font_stack(font["text"]), "color": scheme["ink"]},
            },
            "modebar": {
                "bgcolor": "rgba(0,0,0,0)",
                "color": scheme["ink_muted"],
                "activecolor": scheme["accent"],
            },
            "margin": {"l": 48, "r": 24, "t": 48, "b": 40},
            "geo": {
                "bgcolor": "rgba(0,0,0,0)",
                "landcolor": data["state"]["not_assessed"],
                "showframe": False,
            },
        },
        # Not Plotly template keys: the data colours the client applies to
        # traces by their meta role, to the phase shapes by legend group and
        # to the threshold shapes by name when it switches scheme.
        "data": {
            "series": list(data["series"]),
            "index": dict(data["index"]),
            "state": dict(data["state"]),
            "state_mark": dict(data["state_mark"]),
            "threshold": data["threshold"],
            "outline": scheme["ink_muted"],
            "bands": band_fills(data),
            "map_border": data["map"][border_key],
        },
    }


def build_templates(tokens: dict) -> dict:
    return {name: build_template(tokens, name) for name in ("light", "dark")}


def _json_literal(value) -> str:
    return json.dumps(value, indent=2, ensure_ascii=False, sort_keys=False)


def build_python(tokens: dict) -> str:
    templates = build_templates(tokens)
    return (
        f'"""{HEADER}\n'
        "\n"
        "``TOKENS`` is design/tokens.json as parsed; ``TEMPLATES`` holds the\n"
        "light and dark Plotly templates built from it. ``src.theme`` reads\n"
        "both; the browser receives ``TEMPLATES`` to switch schemes in place.\n"
        '"""\n'
        "\n"
        "import json\n"
        "\n"
        'TOKENS: dict = json.loads(\n    r"""\n' + _json_literal(tokens) + '\n"""\n)\n'
        "\n"
        'TEMPLATES: dict = json.loads(\n    r"""\n' + _json_literal(templates) + '\n"""\n)\n'
    )


def outputs(tokens: dict | None = None) -> dict[Path, str]:
    tokens = tokens if tokens is not None else load_tokens()
    return {CSS_PATH: build_css(tokens), TEMPLATE_PATH: build_python(tokens)}


def main(argv: list[str]) -> int:
    check = "--check" in argv
    stale: list[Path] = []
    for path, text in outputs().items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == text:
            print(f"{path.relative_to(ROOT)}: up to date")
            continue
        stale.append(path)
        if check:
            print(f"{path.relative_to(ROOT)}: STALE")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
            print(f"{path.relative_to(ROOT)}: written")
    return 1 if (check and stale) else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
