"""Generated by scripts/build_tokens.py from design/tokens.json. Do not edit by hand.

``TOKENS`` is design/tokens.json as parsed; ``TEMPLATES`` holds the
light and dark Plotly templates built from it. ``src.theme`` reads
both; the browser receives ``TEMPLATES`` to switch schemes in place.
"""

import json

TOKENS: dict = json.loads(
    r"""
{
  "_comment": [
    "Single source of truth for the atlas design system.",
    "scripts/build_tokens.py emits assets/tokens.css and src/plotly_template.py;",
    "tests/test_tokens.py fails when either is stale. Colours are sRGB hex.",
    "The ENSO phase hues come from the Okabe-Ito set and are drawn only as",
    "low-opacity bands; the three-state hues stay distinct from them."
  ],
  "font": {
    "display": {
      "family": "Source Serif 4",
      "file": "SourceSerif4-latin.woff2",
      "weight_range": "400 700",
      "fallback": "Georgia, 'Times New Roman', serif",
      "licence": "SIL Open Font License 1.1"
    },
    "text": {
      "family": "Source Sans 3",
      "file": "SourceSans3-latin.woff2",
      "weight_range": "300 700",
      "fallback": "'Segoe UI', Helvetica, Arial, sans-serif",
      "licence": "SIL Open Font License 1.1"
    },
    "base_px": 17,
    "ratio": 1.25,
    "steps": {
      "xs": -2,
      "sm": -1,
      "md": 0,
      "lg": 1,
      "xl": 2,
      "2xl": 3,
      "3xl": 4
    },
    "line_height": {
      "body": 1.55,
      "tight": 1.2,
      "display": 1.1
    },
    "measure": "68ch",
    "figure_font_px": 13
  },
  "space": {
    "unit_px": 8,
    "steps": [
      1,
      2,
      3,
      4,
      5,
      6,
      8,
      12
    ]
  },
  "layout": {
    "content_max_px": 1100,
    "figure_height_px": 420,
    "map_height_px": 460,
    "hairline_px": 1,
    "radius_px": 4,
    "nav_height_px": 48,
    "target_min_px": 44,
    "breakpoint_md_px": 768,
    "breakpoint_lg_px": 1024
  },
  "motion": {
    "fast_ms": 150,
    "base_ms": 200,
    "easing": "cubic-bezier(0.2, 0, 0, 1)"
  },
  "scheme": {
    "light": {
      "paper": "#F9F6F0",
      "surface": "#FFFDF9",
      "ink": "#1C1B19",
      "ink_muted": "#5F5B55",
      "rule": "#DAD5CB",
      "accent": "#0B5C8C",
      "accent_ink": "#FFFFFF",
      "skeleton": "#ECE7DD",
      "focus": "#0B5C8C",
      "error": "#B3213A",
      "error_surface": "#FBEDEF"
    },
    "dark": {
      "paper": "#15171A",
      "surface": "#1D2024",
      "ink": "#ECE8E1",
      "ink_muted": "#B0AAA0",
      "rule": "#33373D",
      "accent": "#8CC4EA",
      "accent_ink": "#15171A",
      "skeleton": "#2A2E34",
      "focus": "#8CC4EA",
      "error": "#F0788C",
      "error_surface": "#3A2227"
    }
  },
  "data": {
    "phase": {
      "el_nino": "#E69F00",
      "la_nina": "#56B4E9",
      "neutral": "#999999"
    },
    "phase_opacity": {
      "el_nino": 0.26,
      "la_nina": 0.2
    },
    "phase_opacity_dark": {
      "el_nino": 0.38,
      "la_nina": 0.3
    },
    "phase_outline": {
      "el_nino": null,
      "la_nina": "dot"
    },
    "state": {
      "alert": "#C8324D",
      "no_alert": "#0E8064",
      "not_assessed": "#8F8A82"
    },
    "state_mark": {
      "alert": "filled",
      "no_alert": "outlined",
      "not_assessed": "hatched"
    },
    "series": [
      "#0072B2",
      "#D55E00",
      "#009E73",
      "#A8529B",
      "#7A6A00"
    ],
    "index": {
      "primary": "#0072B2",
      "secondary": "#86817A"
    },
    "threshold": "#86817A",
    "map": {
      "border_light": "#FFFFFF",
      "border_dark": "#15171A"
    }
  }
}
"""
)

TEMPLATES: dict = json.loads(
    r"""
{
  "light": {
    "layout": {
      "paper_bgcolor": "#FFFDF9",
      "plot_bgcolor": "#FFFDF9",
      "font": {
        "family": "\"Source Sans 3\", 'Segoe UI', Helvetica, Arial, sans-serif",
        "color": "#1C1B19",
        "size": 13
      },
      "title": {
        "font": {
          "family": "\"Source Serif 4\", Georgia, 'Times New Roman', serif",
          "color": "#1C1B19"
        }
      },
      "colorway": [
        "#0072B2",
        "#D55E00",
        "#009E73",
        "#A8529B",
        "#7A6A00"
      ],
      "xaxis": {
        "gridcolor": "#DAD5CB",
        "zerolinecolor": "#DAD5CB",
        "linecolor": "#DAD5CB",
        "tickcolor": "#5F5B55",
        "tickfont": {
          "color": "#5F5B55"
        },
        "title": {
          "font": {
            "color": "#5F5B55"
          }
        },
        "automargin": true
      },
      "yaxis": {
        "gridcolor": "#DAD5CB",
        "zerolinecolor": "#DAD5CB",
        "linecolor": "#DAD5CB",
        "tickcolor": "#5F5B55",
        "tickfont": {
          "color": "#5F5B55"
        },
        "title": {
          "font": {
            "color": "#5F5B55"
          }
        },
        "automargin": true
      },
      "legend": {
        "bgcolor": "rgba(0,0,0,0)",
        "font": {
          "color": "#1C1B19"
        },
        "itemclick": "toggleothers",
        "itemdoubleclick": "toggle"
      },
      "hoverlabel": {
        "bgcolor": "#FFFDF9",
        "bordercolor": "#DAD5CB",
        "font": {
          "family": "\"Source Sans 3\", 'Segoe UI', Helvetica, Arial, sans-serif",
          "color": "#1C1B19"
        }
      },
      "modebar": {
        "bgcolor": "rgba(0,0,0,0)",
        "color": "#5F5B55",
        "activecolor": "#0B5C8C"
      },
      "margin": {
        "l": 48,
        "r": 24,
        "t": 48,
        "b": 40
      },
      "geo": {
        "bgcolor": "rgba(0,0,0,0)",
        "landcolor": "#8F8A82",
        "showframe": false
      }
    },
    "bands": {
      "el_nino": "rgba(230,159,0,0.26)",
      "la_nina": "rgba(86,180,233,0.2)"
    }
  },
  "dark": {
    "layout": {
      "paper_bgcolor": "#1D2024",
      "plot_bgcolor": "#1D2024",
      "font": {
        "family": "\"Source Sans 3\", 'Segoe UI', Helvetica, Arial, sans-serif",
        "color": "#ECE8E1",
        "size": 13
      },
      "title": {
        "font": {
          "family": "\"Source Serif 4\", Georgia, 'Times New Roman', serif",
          "color": "#ECE8E1"
        }
      },
      "colorway": [
        "#0072B2",
        "#D55E00",
        "#009E73",
        "#A8529B",
        "#7A6A00"
      ],
      "xaxis": {
        "gridcolor": "#33373D",
        "zerolinecolor": "#33373D",
        "linecolor": "#33373D",
        "tickcolor": "#B0AAA0",
        "tickfont": {
          "color": "#B0AAA0"
        },
        "title": {
          "font": {
            "color": "#B0AAA0"
          }
        },
        "automargin": true
      },
      "yaxis": {
        "gridcolor": "#33373D",
        "zerolinecolor": "#33373D",
        "linecolor": "#33373D",
        "tickcolor": "#B0AAA0",
        "tickfont": {
          "color": "#B0AAA0"
        },
        "title": {
          "font": {
            "color": "#B0AAA0"
          }
        },
        "automargin": true
      },
      "legend": {
        "bgcolor": "rgba(0,0,0,0)",
        "font": {
          "color": "#ECE8E1"
        },
        "itemclick": "toggleothers",
        "itemdoubleclick": "toggle"
      },
      "hoverlabel": {
        "bgcolor": "#1D2024",
        "bordercolor": "#33373D",
        "font": {
          "family": "\"Source Sans 3\", 'Segoe UI', Helvetica, Arial, sans-serif",
          "color": "#ECE8E1"
        }
      },
      "modebar": {
        "bgcolor": "rgba(0,0,0,0)",
        "color": "#B0AAA0",
        "activecolor": "#8CC4EA"
      },
      "margin": {
        "l": 48,
        "r": 24,
        "t": 48,
        "b": 40
      },
      "geo": {
        "bgcolor": "rgba(0,0,0,0)",
        "landcolor": "#8F8A82",
        "showframe": false
      }
    },
    "bands": {
      "el_nino": "rgba(230,159,0,0.38)",
      "la_nina": "rgba(86,180,233,0.3)"
    }
  }
}
"""
)
